# deploy.yml file for GitHub Actions
name: Deploy Docs

on: [push, pull_request]

jobs:
    deploy_docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2

            - name: Retrieve the cached "node_modules" directory (if present)
              uses: actions/cache@v2
              id: node-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies (if the cached directory was not found)
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Generate TypeDoc
              run: npx typedoc

            - name: Generate VitePress
              run: vitepress build docs

            - name: Create site dir
              run: |
                  mkdir docsite
                  mv ts-docs docsite
                  mv vite-docs docsite

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: docsite
                  token: ${{ secrets.DOCSTOKEN }}
